import {test} from 'node:test';import assert from 'node:assert/strict';import {newPlan,samplePlan,calculate,geometry,importPlan} from './calculations.js';
test('multiple rooms and partial-height deductions',()=>{const p=samplePlan();const g=geometry(p.rooms);assert.deepEqual(g,{floor:360,wall:224,trim:65,perimeter:106,errors:[]});});
test('waste adds only to materials',()=>{const c=calculate(samplePlan());const row=c.rows.find(r=>r.id==='drywall');assert.equal(row.qty,224);assert.ok(Math.abs(row.mq-246.4)<1e-8);assert.equal(row.labor,560);assert.ok(Math.abs(row.material-295.68)<1e-8);assert.equal(c.complete,true);});
test('unknown prices are incomplete, explicit zero is priced',()=>{const p=samplePlan();p.items.drywall.material='';let c=calculate(p);assert.equal(c.complete,false);assert.ok(c.missing.includes('Drywall material price'));p.items.drywall.material='0';assert.equal(calculate(p).complete,true);});
test('percentages are sequential, fixed charges counted once',()=>{const p=samplePlan('contractor');p.charges=[{name:'Permit',amount:'100'}];p.percent={overhead:'10',profit:'20',contingency:'5',tax:'8'};const c=calculate(p);assert.equal(c.fixed,100);assert.equal(c.direct,c.materials+c.labor+100);const round=v=>Math.round((v+Number.EPSILON)*100)/100;assert.equal(c.overhead,round(c.direct*.1));assert.equal(c.profit,round((c.direct+c.overhead)*.2));assert.equal(c.contingency,round((c.direct+c.overhead+c.profit)*.05));assert.equal(c.tax,round((c.direct+c.overhead+c.profit+c.contingency)*.08));assert.equal(c.total,round(c.direct+c.overhead+c.profit+c.contingency+c.tax));});
test('invalid and missing measurements are blocked',()=>{const p=newPlan();assert.ok(calculate(p).errors.length);const s=samplePlan();s.rooms[0].repairHeight='9';s.rooms[0].affected='100';s.rooms[1].wallDeduction='100';s.items.flooring.quantity='-1';s.percent.tax='-3';const c=calculate(s);assert.ok(c.errors.some(x=>x.includes('ceiling')));assert.ok(c.errors.some(x=>x.includes('perimeter')));assert.ok(c.errors.some(x=>x.includes('deductions')));assert.ok(c.errors.some(x=>x.includes('quantity')));assert.ok(c.errors.some(x=>x.includes('tax')));assert.equal(c.complete,false);});
test('plan export/import preserves data and rejects bad structures',()=>{const p=samplePlan('contractor');p.items.drywall.quantity='200';p.business='Test Builder';assert.deepEqual(importPlan(JSON.stringify(p)),p);for(const bad of ['{}','null','{bad',JSON.stringify({...p,version:3}),JSON.stringify({...p,items:{}}),JSON.stringify({...p,rooms:[{}]})])assert.throws(()=>importPlan(bad));});

test('currency rounds each cost and percentage to cents',()=>{const p=samplePlan();p.items.drywall.material='0.333333';p.percent.overhead='12.345';const c=calculate(p);assert.equal(c.rows[0].material,82.13);assert.equal(c.overhead,Math.round((c.direct*0.12345+Number.EPSILON)*100)/100);});
