import {stageCatalog,stageItems,defaultStages} from './stages.js';
export {stageCatalog,stageItems} from './stages.js';
export const catalog = [
 ['drywall','Drywall','sq ft','Replace damaged wallboard; finish joints ready for paint.',true],
 ['insulation','Insulation','sq ft','Replace insulation behind affected wallboard.',true],
 ['flooring','Flooring','sq ft','New floor covering in the affected floor area.',true],
 ['baseboards','Baseboards','linear ft','Replace trim along affected walls.',true],
 ['painting','Painting','sq ft','Paint the repaired wall area; excludes ceilings.',true],
 ['demolition','Damaged drywall removal','sq ft','Wallboard removal only. Floor covering and trench concrete are separate items.',false],
 ['debris','Debris hauling & disposal','job','One project-wide haul-away charge. Do not repeat included dumpster or disposal fees.',false],
 ['studs','Stud repair / replacement','stud','Contractor-entered quantity, independent from stud demolition.',true]
];
export function roomId(){if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')return crypto.randomUUID();const bytes=new Uint8Array(16);if(typeof crypto!=='undefined'&&typeof crypto.getRandomValues==='function')crypto.getRandomValues(bytes);else for(let i=0;i<16;i++)bytes[i]=Math.floor(Math.random()*256);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>('0'+b.toString(16)).slice(-2)).join('');return hex.slice(0,8)+'-'+hex.slice(8,12)+'-'+hex.slice(12,16)+'-'+hex.slice(16,20)+'-'+hex.slice(20);}
export const blankRoom=(name='Basement room')=>({id:roomId(),name,length:'',width:'',height:'8',affected:'',repairHeight:'4',wallDeduction:'0',floorDeduction:'0',trimDeduction:'0',removalHeight:'4',removalDeduction:'0'});
export function newPlan(role='homeowner'){return {version:2,role,project:'My basement repair',business:'',notes:'',rooms:[blankRoom()],items:Object.fromEntries(catalog.map(([id,,,,material])=>[id,{selected:['drywall','insulation','painting','demolition','debris'].includes(id),quantity:'',material:material?'':'0',labor:'',waste:material?'10':'0'}])),charges:[],percent:{overhead:'0',profit:'0',contingency:'0',tax:'0'},stages:defaultStages(),status:{dryingVerified:false,concreteReady:false},example:false};}
export const validNumber=v=>(typeof v==='number'||typeof v==='string')&&String(v).trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0;
const n=v=>validNumber(v)?Number(v):0;
export const cents=v=>Math.round((v+Number.EPSILON)*100)/100;
export function geometry(rooms){let floor=0,wall=0,trim=0,perimeter=0;const errors=[];rooms.forEach((r,i)=>{const label=r.name||`Room ${i+1}`;for(const k of ['length','width','height','affected','repairHeight','wallDeduction','floorDeduction','trimDeduction'])if(!validNumber(r[k])||(['length','width','height'].includes(k)&&n(r[k])<=0))errors.push(`${label}: enter a valid ${k.replace(/([A-Z])/g,' $1').toLowerCase()}.`);const l=n(r.length),w=n(r.width),h=n(r.height),a=n(r.affected),rh=n(r.repairHeight),p=2*(l+w);if(a>p)errors.push(`${label}: affected wall length exceeds the room perimeter.`);if(rh>h)errors.push(`${label}: repair height exceeds ceiling height.`);if(n(r.wallDeduction)>a*rh)errors.push(`${label}: wall deductions exceed affected wall area.`);if(n(r.floorDeduction)>l*w)errors.push(`${label}: floor deductions exceed floor area.`);if(n(r.trimDeduction)>a)errors.push(`${label}: trim deductions exceed affected wall length.`);floor+=Math.max(0,l*w-n(r.floorDeduction));wall+=Math.max(0,a*rh-n(r.wallDeduction));trim+=Math.max(0,a-n(r.trimDeduction));perimeter+=p;});return {floor,wall,trim,perimeter,errors};}
export function demolitionGeometry(rooms){let wall=0;const errors=[];for(const r of rooms){const height=r.removalHeight??r.repairHeight,deduction=r.removalDeduction??r.wallDeduction;if(!validNumber(height))errors.push(`${r.name}: enter a valid drywall removal height.`);if(!validNumber(deduction))errors.push(`${r.name}: enter a valid demolition opening deduction.`);if(n(height)>n(r.height))errors.push(`${r.name}: drywall removal height exceeds ceiling height.`);if(n(deduction)>n(r.affected)*n(height))errors.push(`${r.name}: demolition deductions exceed removal area.`);wall+=Math.max(0,n(r.affected)*n(height)-n(deduction));}return {wall,errors};}
export function drainageGeometry(d){const errors=[];const needed=[['length','actual drainage length',false],['width','trench width',true],['depth','total trench depth',true],['slabThickness','existing slab thickness',false]];for(const [k,label,positive]of needed)if(!validNumber(d[k])||(positive&&n(d[k])<=0))errors.push(`Drainage: enter ${label}${positive?' greater than zero':''}.`);if(n(d.slabThickness)>n(d.depth))errors.push('Drainage: slab thickness cannot exceed total trench depth.');if(d.gravelFillDepth!==''&&(!validNumber(d.gravelFillDepth)||n(d.gravelFillDepth)>Math.max(0,n(d.depth)-n(d.slabThickness))))errors.push('Drainage: gravel fill depth must fit in the space beneath the slab.');const l=n(d.length),w=n(d.width)/12,depth=n(d.depth)/12,slab=n(d.slabThickness)/12;return {errors,drainLength:l,cutLength:l*2,trenchArea:l*w,trenchVolume:l*w*depth/27,slabVolume:l*w*slab/27,excavationVolume:l*w*Math.max(0,depth-slab)/27,gravelVolume:d.gravelFillDepth!==''&&validNumber(d.gravelFillDepth)?l*w*n(d.gravelFillDepth)/12/27:null,sumps:d.useSumpRule?(l>0?Math.ceil(l/100):0):null};}
export function concreteGeometry(c,d){const length=c.length===''?d.length:c.length,errors=[];for(const [label,v]of [['patch length',length],['patch width',c.width],['patch thickness',c.thickness]])if(!validNumber(v)||(label!=='patch length'&&n(v)<=0))errors.push(`Concrete: enter a valid ${label}${label!=='patch length'?' greater than zero':''}.`);const l=n(length),w=n(c.width)/12,t=n(c.thickness)/12;return {errors,length:l,width:w,thickness:t,patchArea:l*w,concreteVolume:l*w*t/27};}
const legacyStage=id=>['demolition','debris'].includes(id)?'demolition':'reconstruction';
function normalizeLegacy(p){if(p.stages)return p;const stages=defaultStages();stages.demolition.selected=['demolition','debris'].some(id=>p.items[id].selected);stages.reconstruction.selected=catalog.slice(0,5).some(([id])=>p.items[id].selected);return {...p,version:2,stages,status:{dryingVerified:false,concreteReady:false},items:{...p.items,studs:{selected:false,quantity:'',material:'',labor:'',waste:'10'}},rooms:p.rooms.map(r=>({...r,removalHeight:r.repairHeight,removalDeduction:r.wallDeduction}))};}
export function calculate(input){const plan=normalizeLegacy(input),g=geometry(plan.rooms),demolition=demolitionGeometry(plan.rooms),drainage=drainageGeometry(plan.stages.drainage),concrete=concreteGeometry(plan.stages.concrete,plan.stages.drainage),errors=[],missing=[],rows=[];
const usesRooms=plan.stages.reconstruction.selected||plan.stages.demolition.selected;if(usesRooms)errors.push(...g.errors);if(plan.stages.demolition.selected)errors.push(...demolition.errors);if(plan.stages.drainage.selected)errors.push(...drainage.errors);if(plan.stages.concrete.selected)errors.push(...concrete.errors);
const quantities={one:1,floor:g.floor,wall:g.wall,trim:g.trim,demolitionWall:demolition.wall,...drainage,...concrete};
function addRow({id,label,unit,kind,auto,item,stage,path,desc}){const raw=item.quantity===''?auto:item.quantity;let q=validNumber(raw)?Number(raw):0;if(!validNumber(raw))errors.push(`${label}: enter a quantity or complete its estimating assumptions.`);let days=1;if(kind==='equipment'){if(!validNumber(item.days)||n(item.days)<=0)errors.push(`${label}: enter rental days greater than zero.`);days=n(item.days);if(!Number.isInteger(q))errors.push(`${label}: equipment count must be a whole number.`);}
if(['basins','pumps','studs','demolition.studRemoval'].some(k=>id===k||id===`drainage.${k}`)&&!Number.isInteger(q))errors.push(`${label}: quantity must be a whole number.`);
const hasMaterial=['combined','material'].includes(kind),hasLabor=['combined','labor'].includes(kind),hasRate=['equipment','fixed'].includes(kind);for(const k of [...(hasMaterial?['material','waste']:[]),...(hasLabor?['labor']:[]),...(hasRate?['rate']:[])])if(item[k]!==''&&!validNumber(item[k]))errors.push(`${label}: invalid ${k} value.`);
const waste=hasMaterial?n(item.waste):0,mq=q*(1+waste/100),needsPrice=q>0||!validNumber(raw),mp=hasMaterial&&needsPrice&&String(item.material).trim()==='',lp=hasLabor&&needsPrice&&String(item.labor).trim()==='',rp=hasRate&&needsPrice&&String(item.rate).trim()==='';if(mp)missing.push(`${label} material price`);if(lp)missing.push(`${label} labor price`);if(rp)missing.push(`${label} ${kind==='equipment'?'daily rental':'unit'} price`);
const material=hasMaterial&&!mp?cents(mq*n(item.material)):0,labor=hasLabor&&!lp?cents(q*n(item.labor)):0,equipment=kind==='equipment'&&!rp?cents(q*days*n(item.rate)):0,fixed=kind==='fixed'&&!rp?cents(q*n(item.rate)):0,payer=kind==='equipment'?item.payer:'contractor',total=cents(material+labor+equipment+fixed);rows.push({id,label,unit,kind,auto,qty:q,mq,waste,hasMaterial,hasLabor,hasRate,days,priceQty:kind==='equipment'?q*days:q,material,labor,equipment,fixed,total,mp,lp,rp,payer,stage,path,desc,item,unpriced:mp||lp||rp,invalidQuantity:!validNumber(raw)});}
for(const [id,label,unit,desc,hasMaterial]of catalog){const item=plan.items[id],stage=legacyStage(id);if(!plan.stages[stage].selected||!item.selected)continue;const auto=id==='flooring'?g.floor:id==='baseboards'?g.trim:id==='debris'?1:id==='demolition'?demolition.wall:id==='studs'?null:g.wall;addRow({id,label,unit,desc,kind:hasMaterial?'combined':'labor',auto,item,stage,path:`items.${id}`});}
for(const [stage,defs]of Object.entries(stageItems)){if(!plan.stages[stage].selected)continue;for(const [id,label,unit,kind,autoKey,desc]of defs){const item=plan.stages[stage].items[id];if(item.selected)addRow({id:`${stage}.${id}`,label,unit,kind,auto:autoKey?quantities[autoKey]:null,item,stage,path:`stages.${stage}.items.${id}`,desc});}}
let materials=0,labor=0,equipment=0,fixed=0,homeownerPaid=0;for(const r of rows){if(r.payer==='homeowner')homeownerPaid+=r.total;else{materials+=r.material;labor+=r.labor;equipment+=r.equipment;fixed+=r.fixed;}}for(const c of plan.charges){if(String(c.amount).trim()==='')missing.push(`${c.name||'Unnamed charge'} price`);else if(!validNumber(c.amount))errors.push('Fixed charges must be zero or greater.');else fixed+=cents(n(c.amount));}for(const [k,v]of Object.entries(plan.percent))if(!validNumber(v))errors.push(`${k}: enter a valid percentage.`);
materials=cents(materials);labor=cents(labor);equipment=cents(equipment);fixed=cents(fixed);homeownerPaid=cents(homeownerPaid);const direct=cents(materials+labor+equipment+fixed),overhead=cents(direct*n(plan.percent.overhead)/100),profit=cents((direct+overhead)*n(plan.percent.profit)/100),contingency=cents((direct+overhead+profit)*n(plan.percent.contingency)/100),tax=cents((direct+overhead+profit+contingency)*n(plan.percent.tax)/100),total=cents(direct+overhead+profit+contingency+tax);
const stages=stageCatalog.map(([id,label,desc])=>{const stageRows=rows.filter(r=>r.stage===id),contractor=stageRows.filter(r=>r.payer!=='homeowner'),sum=(rs,key)=>cents(rs.reduce((s,r)=>s+r[key],0));return {id,label,desc,selected:plan.stages[id].selected,rows:stageRows,materials:sum(contractor,'material'),labor:sum(contractor,'labor'),equipment:sum(contractor,'equipment'),fixed:sum(contractor,'fixed'),contractorSubtotal:sum(contractor,'total'),homeownerPaid:sum(stageRows.filter(r=>r.payer==='homeowner'),'total'),unpriced:stageRows.some(r=>r.unpriced),invalidQuantity:stageRows.some(r=>r.invalidQuantity)};});
const homeownerMissing=rows.filter(r=>r.payer==='homeowner'&&r.unpriced).map(r=>r.label),contractorMissing=missing.length-homeownerMissing.length;
const warnings=[];if(plan.stages.reconstruction.selected&&!plan.status.dryingVerified)warnings.push('Drying has not been verified by a contractor. This estimate does not confirm readiness for reconstruction.');if(plan.stages.concrete.selected&&plan.stages.reconstruction.selected&&plan.items.flooring.selected&&!plan.status.concreteReady)warnings.push('Contractor confirmation of concrete readiness is still needed before new flooring installation.');if(plan.stages.drying.selected)warnings.push('Equipment counts and rental duration are estimating allowances. Three days does not guarantee a dry basement.');if(plan.stages.demolition.selected&&plan.items.debris.selected&&plan.stages.demolition.items.dumpster.selected)warnings.push('Confirm that dumpster and disposal charges are not already included in debris hauling.');if(!stages.some(s=>s.selected)&&!plan.charges.length)warnings.push('No work stages are included. Select the work needed for this project.');
return {g,demolition,drainage,concrete,rows,stages,errors:[...new Set(errors)],missing,homeownerMissing,contractorMissing,materials,labor,equipment,fixed,direct,overhead,profit,contingency,tax,total,homeownerPaid,projectTotal:cents(total+homeownerPaid),quoteComplete:!errors.length&&!contractorMissing,complete:!errors.length&&!missing.length,warnings};}
export function importPlan(text){const p=JSON.parse(text),scalar=v=>typeof v==='string'||typeof v==='number',fail=()=>{throw Error('This is not a supported RebuildReady plan.');};if(!p||![1,2].includes(p.version)||!['homeowner','contractor'].includes(p.role)||!Array.isArray(p.rooms)||!p.rooms.length||p.rooms.length>100||!p.items||!p.percent||!Array.isArray(p.charges)||p.charges.length>200)fail();for(const k of ['project','business','notes'])if(typeof p[k]!=='string')fail();for(const r of p.rooms){if(typeof r.name!=='string'||typeof r.id!=='string')fail();for(const k of ['length','width','height','affected','repairHeight','wallDeduction','floorDeduction','trimDeduction'])if(!scalar(r[k]))fail();}for(const [id]of catalog.slice(0,7)){const i=p.items[id];if(!i||typeof i.selected!=='boolean'||!['quantity','material','labor','waste'].every(k=>scalar(i[k])))fail();}for(const k of ['overhead','profit','contingency','tax'])if(!scalar(p.percent[k]))fail();for(const c of p.charges)if(typeof c.name!=='string'||!scalar(c.amount))fail();if(p.version===1){if(p.stages)fail();return normalizeLegacy(p);}if(!p.stages||!p.status||typeof p.status.dryingVerified!=='boolean'||typeof p.status.concreteReady!=='boolean')fail();for(const r of p.rooms)if(!scalar(r.removalHeight)||!scalar(r.removalDeduction))fail();const stud=p.items.studs;if(!stud||typeof stud.selected!=='boolean'||!['quantity','material','labor','waste'].every(k=>scalar(stud[k])))fail();for(const [id]of stageCatalog){const s=p.stages[id];if(!s||typeof s.selected!=='boolean'||!s.items)fail();for(const [itemId]of stageItems[id]||[]){const item=s.items[itemId];if(!item||typeof item.selected!=='boolean'||!['quantity','days','rate','material','labor','waste'].every(k=>scalar(item[k]))||!['contractor','homeowner'].includes(item.payer))fail();}}for(const k of ['length','width','depth','slabThickness','gravelFillDepth'])if(!scalar(p.stages.drainage[k]))fail();if(typeof p.stages.drainage.useSumpRule!=='boolean'||typeof p.stages.drying.overlap!=='boolean')fail();for(const k of ['length','width','thickness'])if(!scalar(p.stages.concrete[k]))fail();return p;}
export function samplePlan(role='homeowner'){const p=newPlan(role);p.project='Maple Street · Basement rebuild';p.example=true;p.rooms=[{...blankRoom('Family room'),length:'20',width:'15',height:'8',affected:'50',repairHeight:'4',wallDeduction:'12',floorDeduction:'0',trimDeduction:'3',removalHeight:'4',removalDeduction:'12'},{...blankRoom('Laundry room'),length:'10',width:'8',height:'8',affected:'18',repairHeight:'2',wallDeduction:'0',floorDeduction:'20',trimDeduction:'0',removalHeight:'2',removalDeduction:'0'}];const prices={drywall:[1.2,2.5],insulation:[0.9,1.1],flooring:[3.5,2.2],baseboards:[1.8,1.7],painting:[0.45,1.4],demolition:[0,1.2],debris:[0,275]};for(const[id]of catalog.slice(0,7)){p.items[id].selected=true;p.items[id].material=String(prices[id][0]);p.items[id].labor=String(prices[id][1]);}p.notes='Example project: four-foot wall repairs in the family room and two-foot repairs in the laundry. Confirm substrate condition and material choices during inspection.';return p;}
export function restorationSample(role='homeowner'){const p=samplePlan(role);p.project='Maple Street · Full basement restoration';for(const s of Object.values(p.stages))s.selected=true;p.rooms[1].removalHeight='4';const set=(stage,id,values)=>Object.assign(p.stages[stage].items[id],{selected:true},values);set('water','pump',{quantity:'1',days:'1',rate:'85'});set('water','hoses',{quantity:'2',days:'1',rate:'8'});set('water','delivery',{rate:'75'});set('water','setup',{quantity:'2',labor:'55'});set('water','monitoring',{quantity:'1',labor:'55'});set('water','removal',{quantity:'1',labor:'55'});set('drying','dehumidifiers',{quantity:'2',days:'3',rate:'65',payer:'homeowner'});set('drying','airMovers',{quantity:'3',days:'3',rate:'20'});set('drying','delivery',{rate:'85'});set('drying','monitoring',{quantity:'3',labor:'55'});set('demolition','floorRemoval',{labor:'1.5'});set('demolition','insulationRemoval',{labor:'0.5'});set('demolition','trimRemoval',{labor:'0.8'});set('demolition','studRemoval',{quantity:'4',labor:'8'});Object.assign(p.stages.drainage,{length:'110',width:'18',depth:'15',slabThickness:'4',gravelFillDepth:'8',useSumpRule:true});for(const[id]of stageItems.drainage){const v={cutting:{labor:'3'},slabRemoval:{labor:'5'},excavation:{labor:'90'},slabHauling:{rate:'125'},soilHauling:{rate:'65'},gravel:{material:'85',waste:'10'},pipe:{material:'4',labor:'8'},fittings:{quantity:'8',material:'12'},basins:{material:'175',labor:'150'},pumps:{material:'280',labor:'125'},discharge:{quantity:'35',material:'3',labor:'5'},connections:{quantity:'2',material:'20',labor:'25'},backup:{rate:'450'},electrical:{rate:'325'}}[id];set('drainage',id,v);}set('concrete','concrete',{material:'180',labor:'120'});set('concrete','delivery',{rate:'200'});set('concrete','finishing',{labor:'2.5'});p.items.studs={selected:true,quantity:'6',material:'9',labor:'18',waste:'10'};p.notes='DEMONSTRATION ONLY: all rates are example prices, not local market estimates. Drainage length is entered independently of room perimeters. See each rental line for current equipment counts, days, and payment responsibility. Contractor review and readiness verification remain outstanding.';return p;}
