import {test} from 'node:test';import assert from 'node:assert/strict';
import {newPlan,samplePlan,restorationSample,calculate,importPlan,drainageGeometry,concreteGeometry,cents} from './calculations.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function onlyStage(id){const p=restorationSample('contractor');for(const[k,s]of Object.entries(p.stages))s.selected=k===id;return p;}
test('equipment costs use units times days times daily rate',()=>{const p=onlyStage('drying');const c=calculate(p),r=c.rows.find(r=>r.id==='drying.dehumidifiers');assert.equal(r.qty,2);assert.equal(r.days,3);assert.equal(r.priceQty,6);assert.equal(r.equipment,390);p.stages.drying.items.dehumidifiers.quantity='3';assert.equal(calculate(p).rows.find(r=>r.id==='drying.dehumidifiers').equipment,585);});
test('homeowner rentals are excluded from all contractor additions',()=>{const p=onlyStage('drying');p.percent={overhead:'10',profit:'20',contingency:'5',tax:'8'};const c=calculate(p);assert.equal(c.homeownerPaid,390);assert.equal(c.equipment,180);assert.equal(c.labor,165);assert.equal(c.fixed,85);assert.equal(c.direct,430);assert.equal(c.overhead,43);assert.equal(c.profit,94.6);assert.equal(c.contingency,28.38);assert.equal(c.tax,47.68);assert.equal(c.total,643.66);assert.equal(c.projectTotal,1033.66);p.stages.drying.items.dehumidifiers.payer='contractor';const moved=calculate(p);assert.equal(moved.homeownerPaid,0);assert.equal(moved.direct,820);assert.equal(moved.overhead,82);});
test('temporary pump and permanent pump counts stay separate',()=>{const p=restorationSample();p.stages.water.items.pump.quantity='3';p.stages.drainage.items.pumps.quantity='1';const c=calculate(p);assert.equal(c.rows.find(r=>r.id==='water.pump').qty,3);assert.equal(c.rows.find(r=>r.id==='drainage.pumps').qty,1);});
test('partial-height demolition uses separate opening deductions',()=>{const p=samplePlan();p.rooms[0].removalHeight='2';p.rooms[0].removalDeduction='6';const c=calculate(p);assert.equal(c.demolition.wall,130);assert.equal(c.rows.find(r=>r.id==='demolition').qty,130);assert.equal(c.rows.find(r=>r.id==='drywall').qty,224);p.items.demolition.quantity='90';assert.equal(calculate(p).rows.find(r=>r.id==='demolition').qty,90);assert.equal(calculate(p).rows.find(r=>r.id==='drywall').qty,224);p.rooms[0].removalHeight='9';assert.ok(calculate(p).errors.some(x=>x.includes('removal height exceeds ceiling')));});
test('inches convert correctly and excavation subtracts existing slab once',()=>{const d=drainageGeometry({length:'100',width:'18',depth:'15',slabThickness:'4',gravelFillDepth:'8',useSumpRule:true});near(d.trenchArea,150);near(d.trenchVolume,150*1.25/27);near(d.slabVolume,150*(4/12)/27);near(d.excavationVolume,150*(11/12)/27);near(d.trenchVolume,d.slabVolume+d.excavationVolume);near(d.gravelVolume,150*(8/12)/27);assert.ok(d.gravelVolume<d.trenchVolume);assert.deepEqual(d.errors,[]);});
test('drainage length is never taken from room perimeters',()=>{const p=onlyStage('drainage');p.stages.drainage.length='';const c=calculate(p);assert.equal(c.drainage.drainLength,0);assert.ok(c.errors.some(x=>x.includes('actual drainage length')));assert.equal(c.drainage.sumps,0);assert.notEqual(c.drainage.drainLength,c.g.perimeter);});
test('one-sump-per-100ft rule rounds up positive lengths and allows separate overrides',()=>{for(const[length,expected]of [['0',0],['0.1',1],['100',1],['100.1',2],['250',3]]){const p=onlyStage('drainage');p.stages.drainage.length=length;const c=calculate(p);assert.equal(c.drainage.sumps,expected);assert.equal(c.rows.find(r=>r.id==='drainage.basins').qty,expected);assert.equal(c.rows.find(r=>r.id==='drainage.pumps').qty,expected);}const p=onlyStage('drainage');p.stages.drainage.items.basins.quantity='3';p.stages.drainage.items.pumps.quantity='1';const c=calculate(p);assert.equal(c.rows.find(r=>r.id==='drainage.basins').qty,3);assert.equal(c.rows.find(r=>r.id==='drainage.pumps').qty,1);p.stages.drainage.useSumpRule=false;p.stages.drainage.items.basins.quantity='';assert.ok(calculate(p).errors.some(x=>x.includes('Sump basins')));});
test('gravel requires explicit quantity or fill depth, manual quantity wins',()=>{const p=onlyStage('drainage');p.stages.drainage.gravelFillDepth='';let c=calculate(p);assert.equal(c.drainage.gravelVolume,null);assert.ok(c.errors.some(x=>x.includes('Drainage gravel')));p.stages.drainage.items.gravel.quantity='3.5';c=calculate(p);assert.equal(c.rows.find(r=>r.id==='drainage.gravel').qty,3.5);p.stages.drainage.gravelFillDepth='8';assert.equal(calculate(p).rows.find(r=>r.id==='drainage.gravel').qty,3.5);});
test('concrete volume uses independent patch thickness, waste never increases labor',()=>{const p=onlyStage('concrete');p.stages.concrete={...p.stages.concrete,length:'100',width:'18',thickness:'4'};const c=calculate(p),r=c.rows.find(r=>r.id==='concrete.concrete');near(c.concrete.patchArea,150);near(c.concrete.concreteVolume,150*(4/12)/27);near(r.mq,r.qty*1.1);assert.equal(r.labor,cents(r.qty*120));p.stages.drainage.depth='24';near(calculate(p).concrete.concreteVolume,c.concrete.concreteVolume);p.stages.concrete.thickness='0';assert.ok(calculate(p).errors.some(x=>x.includes('patch thickness')));});
test('unpriced homeowner costs do not become free or mark contractor quote unpriced',()=>{const p=onlyStage('drying');p.stages.drying.items.dehumidifiers.rate='';let c=calculate(p);assert.equal(c.complete,false);assert.equal(c.quoteComplete,true);assert.equal(c.homeownerMissing.length,1);assert.equal(c.contractorMissing,0);assert.equal(c.rows.find(r=>r.id==='drying.dehumidifiers').unpriced,true);p.stages.drying.items.dehumidifiers.rate='0';c=calculate(p);assert.equal(c.complete,true);assert.equal(c.homeownerPaid,0);assert.equal(c.rows.find(r=>r.id==='drying.dehumidifiers').unpriced,false);p.stages.drying.items.dehumidifiers.selected=false;assert.equal(calculate(p).rows.some(r=>r.id==='drying.dehumidifiers'),false);});
test('old version-1 plans migrate without adding scope or changing totals',()=>{const original=samplePlan();const old=structuredClone(original);old.version=1;delete old.stages;delete old.status;delete old.items.studs;for(const r of old.rooms){delete r.removalHeight;delete r.removalDeduction;}const p=importPlan(JSON.stringify(old));assert.equal(p.version,2);for(const id of ['water','drying','drainage','concrete'])assert.equal(p.stages[id].selected,false);assert.equal(p.items.studs.selected,false);assert.equal(calculate(p).total,calculate(original).total);assert.equal(p.rooms[1].removalHeight,'2');assert.deepEqual(importPlan(JSON.stringify(p)),p);});
test('canonical demolition/hauling items are charged exactly once',()=>{const p=samplePlan();for(const item of Object.values(p.items))item.selected=false;p.items.demolition={...p.items.demolition,selected:true,quantity:'10',labor:'2'};p.items.debris={...p.items.debris,selected:true,labor:'100'};const c=calculate(p);assert.equal(c.rows.filter(r=>r.id==='demolition').length,1);assert.equal(c.rows.filter(r=>r.id==='debris').length,1);assert.equal(c.direct,120);assert.equal(c.stages.find(s=>s.id==='demolition').contractorSubtotal,120);assert.equal(c.stages.find(s=>s.id==='reconstruction').contractorSubtotal,0);p.stages.demolition.selected=false;assert.equal(calculate(p).direct,0);});
test('all-six-stage example is fully priced, internally reconciles, and retains review warnings',()=>{const p=restorationSample();const c=calculate(p);assert.deepEqual(c.errors,[]);assert.deepEqual(c.missing,[]);assert.equal(c.stages.filter(s=>s.selected).length,6);assert.equal(c.stages.reduce((a,s)=>a+s.contractorSubtotal,0),c.direct);assert.equal(c.projectTotal,cents(c.total+c.homeownerPaid));assert.ok(c.warnings.some(s=>s.includes('not been verified')));assert.ok(c.warnings.some(s=>s.includes('concrete readiness')));assert.deepEqual(importPlan(JSON.stringify(p)),p);});
test('malformed new-stage imports and invalid rental values are rejected or flagged',()=>{const p=restorationSample();const bad=structuredClone(p);bad.stages.drying.items.dehumidifiers.payer='unknown';assert.throws(()=>importPlan(JSON.stringify(bad)));p.stages.drying.items.dehumidifiers.days='0';p.stages.water.items.pump.quantity='1.5';p.stages.drainage.slabThickness='20';const c=calculate(p);assert.ok(c.errors.some(s=>s.includes('rental days')));assert.ok(c.errors.some(s=>s.includes('equipment count')));assert.ok(c.errors.some(s=>s.includes('slab thickness')));assert.equal(c.complete,false);});
